LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := WiFiMaxPower
LOCAL_MODULE_TAGS := eng debug
LOCAL_SHARED_LIBRARIES := libcutils
LOCAL_CFLAGS := $(L_CFLAGS)
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := WiFiMaxPower.c
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_EXECUTABLE)
